import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import Hero from '../components/Hero/Hero'
import RecentWork from '../components/RecentWork/RecentWork'
import Second from '../components/Second/Second'
import Third from '../components/ThirdPart/Third'

export default function Home() {
  return (
    <div className="w-full relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <Header/>
        <Hero/>
        <Second/>
        <Third/>
        <RecentWork/>
        <Footer/>
    </div>
  )
}

export const getServerSideProps = async (context) => {

  return {
    props:{

    }
  }
}